debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.loan: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  thymeleaf3.decoupled-logic: true
